# site properties and page defaults
title: CMC lab
subtitle: Computational Machinery of Cognition
description: The overarching research theme of our lab is understanding the computational machinery of cognitive processes.
header: images/background.jpg
footer: images/background.jpg

baseurl: "/cmclab"


# site social media and other links
links:
  email: site@shervinsafavi.com
  orcid: 0000-0002-2868-530X
  google-scholar: 7UlhWxkAAAAJ&hl=en&oi=ao
  github: shervinsafavi
  twitter: neuroprinciples
  youtube: shervinsafavi

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
