- id: doi:10.1016/j.neuron.2022.07.024
  type: paper
  description: Based on a large collection behavioral and neural data, we introduce a radically new perspective to the well-known phenomenon of perceptual multistability. We formulated the phenomenon as a value-based decision-making process that not only synergies with previous accounts, but also offers a more comprehensive treatment of computational and algorithmic facets of perceptual multistability.
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0896627322006699-fx1.jpg
  buttons:
    - type: website
      text: PDF
      link: https://filedn.eu/lTiemQ34dUJF1QIztSMLoPJ/CMC_lab_publications/SafaviDayan_Neuron2022.pdf
  tags:
    - neural computation
    - normative modeling
    - cognition

# ...another source